#!/usr/bin/env python3
"""
Top 200 Global Companies by Market Cap (November 2025)
Comprehensive list for Alpha Vantage data ingestion
"""

TOP_200_COMPANIES = [
    # 1-25: Top 25 Companies
    {"rank": 1, "symbol": "NVDA", "company": "NVIDIA Corporation", "market_cap_tier": "mega"},
    {"rank": 2, "symbol": "MSFT", "company": "Microsoft Corporation", "market_cap_tier": "mega"},
    {"rank": 3, "symbol": "AAPL", "company": "Apple Inc.", "market_cap_tier": "mega"},
    {"rank": 4, "symbol": "GOOG", "company": "Alphabet Inc. (Class C)", "market_cap_tier": "mega"},
    {"rank": 5, "symbol": "GOOGL", "company": "Alphabet Inc. (Class A)", "market_cap_tier": "mega"},
    {"rank": 6, "symbol": "AMZN", "company": "Amazon.com Inc.", "market_cap_tier": "mega"},
    {"rank": 7, "symbol": "META", "company": "Meta Platforms Inc.", "market_cap_tier": "mega"},
    {"rank": 8, "symbol": "AVGO", "company": "Broadcom Inc.", "market_cap_tier": "mega"},
    {"rank": 9, "symbol": "TSM", "company": "Taiwan Semiconductor Manufacturing Co.", "market_cap_tier": "mega"},
    {"rank": 10, "symbol": "TSLA", "company": "Tesla Inc.", "market_cap_tier": "mega"},
    {"rank": 11, "symbol": "TIGXF", "company": "TEAM INTERNET GROUP PLC", "market_cap_tier": "mega"},
    {"rank": 12, "symbol": "BRK.B", "company": "Berkshire Hathaway Inc. (Class B)", "market_cap_tier": "mega"},
    {"rank": 13, "symbol": "BRK.A", "company": "Berkshire Hathaway Inc. (Class A)", "market_cap_tier": "mega"},
    {"rank": 14, "symbol": "JPM", "company": "JPMorgan Chase & Co.", "market_cap_tier": "mega"},
    {"rank": 15, "symbol": "WMT", "company": "Walmart Inc.", "market_cap_tier": "mega"},
    {"rank": 16, "symbol": "ORCL", "company": "Oracle Corporation", "market_cap_tier": "mega"},
    {"rank": 17, "symbol": "TCTZF", "company": "Tencent Holdings Ltd", "market_cap_tier": "mega"},
    {"rank": 18, "symbol": "TCEHY", "company": "Tencent Holdings Ltd (ADR)", "market_cap_tier": "mega"},
    {"rank": 19, "symbol": "LLY", "company": "Eli Lilly and Company", "market_cap_tier": "mega"},
    {"rank": 20, "symbol": "V", "company": "Visa Inc.", "market_cap_tier": "mega"},
    {"rank": 21, "symbol": "BAC", "company": "Bank of America Corporation", "market_cap_tier": "mega"},
    {"rank": 22, "symbol": "MA", "company": "Mastercard Incorporated", "market_cap_tier": "mega"},
    {"rank": 23, "symbol": "XOM", "company": "Exxon Mobil Corporation", "market_cap_tier": "mega"},
    {"rank": 24, "symbol": "TSMWF", "company": "Taiwan Semiconductor Manufacturing Co. (OTC)", "market_cap_tier": "mega"},
    {"rank": 25, "symbol": "NFLX", "company": "Netflix Inc.", "market_cap_tier": "mega"},
    
    # 26-50: Large Cap Tier 1
    {"rank": 26, "symbol": "JNJ", "company": "Johnson & Johnson", "market_cap_tier": "large"},
    {"rank": 27, "symbol": "SSNLF", "company": "Samsung Electronics Co. Ltd", "market_cap_tier": "large"},
    {"rank": 28, "symbol": "601939.SS", "company": "China Construction Bank Corp", "market_cap_tier": "large"},
    {"rank": 29, "symbol": "000660.KS", "company": "SK Hynix Inc.", "market_cap_tier": "large"},
    {"rank": 30, "symbol": "WFC", "company": "Wells Fargo & Co.", "market_cap_tier": "large"},
    {"rank": 31, "symbol": "MU", "company": "Micron Technology Inc.", "market_cap_tier": "large"},
    {"rank": 32, "symbol": "CAT", "company": "Caterpillar Inc.", "market_cap_tier": "large"},
    {"rank": 33, "symbol": "ROG.SW", "company": "Roche Holding Ltd", "market_cap_tier": "large"},
    {"rank": 34, "symbol": "MS", "company": "Morgan Stanley", "market_cap_tier": "large"},
    {"rank": 35, "symbol": "7203.T", "company": "Toyota Motor Corp", "market_cap_tier": "large"},
    {"rank": 36, "symbol": "RMS.PA", "company": "Hermès International", "market_cap_tier": "large"},
    {"rank": 37, "symbol": "300750.SZ", "company": "Contemporary Amperex Technology Co. Ltd", "market_cap_tier": "large"},
    {"rank": 38, "symbol": "AXP", "company": "American Express Co.", "market_cap_tier": "large"},
    {"rank": 39, "symbol": "AZN.L", "company": "AstraZeneca PLC", "market_cap_tier": "large"},
    {"rank": 40, "symbol": "600519.SS", "company": "Kweichow Moutai Co. Ltd", "market_cap_tier": "large"},
    {"rank": 41, "symbol": "NESN.SW", "company": "Nestlé S.A.", "market_cap_tier": "large"},
    {"rank": 42, "symbol": "600941.SS", "company": "China Mobile Ltd", "market_cap_tier": "large"},
    {"rank": 43, "symbol": "HSBA.L", "company": "HSBC Holdings PLC", "market_cap_tier": "large"},
    {"rank": 44, "symbol": "601857.SS", "company": "PetroChina Co. Ltd", "market_cap_tier": "large"},
    {"rank": 45, "symbol": "IHC.AD", "company": "International Holding Company PJSC", "market_cap_tier": "large"},
    {"rank": 46, "symbol": "NOVN.SW", "company": "Novartis AG", "market_cap_tier": "large"},
    {"rank": 47, "symbol": "9984.T", "company": "SoftBank Group Corp", "market_cap_tier": "large"},
    {"rank": 48, "symbol": "601138.SS", "company": "Foxconn Industrial Internet Co. Ltd", "market_cap_tier": "large"},
    {"rank": 49, "symbol": "NOVO_B.CO", "company": "Novo Nordisk A/S", "market_cap_tier": "large"},
    {"rank": 50, "symbol": "RY.TO", "company": "Royal Bank of Canada", "market_cap_tier": "large"},
    
    # 51-75: Large Cap Tier 2
    {"rank": 51, "symbol": "LRCX", "company": "Lam Research Corporation", "market_cap_tier": "large"},
    {"rank": 52, "symbol": "SHOP.TO", "company": "Shopify Inc.", "market_cap_tier": "large"},
    {"rank": 53, "symbol": "DIS", "company": "Walt Disney Company", "market_cap_tier": "large"},
    {"rank": 54, "symbol": "ISRG", "company": "Intuitive Surgical Inc.", "market_cap_tier": "large"},
    {"rank": 55, "symbol": "LIN", "company": "Linde plc", "market_cap_tier": "large"},
    {"rank": 56, "symbol": "PEP", "company": "PepsiCo Inc.", "market_cap_tier": "large"},
    {"rank": 57, "symbol": "ADBE", "company": "Adobe Inc.", "market_cap_tier": "large"},
    {"rank": 58, "symbol": "CRM", "company": "Salesforce Inc.", "market_cap_tier": "large"},
    {"rank": 59, "symbol": "CSCO", "company": "Cisco Systems Inc.", "market_cap_tier": "large"},
    {"rank": 60, "symbol": "PFE", "company": "Pfizer Inc.", "market_cap_tier": "large"},
    {"rank": 61, "symbol": "ABBV", "company": "AbbVie Inc.", "market_cap_tier": "large"},
    {"rank": 62, "symbol": "MCD", "company": "McDonald's Corporation", "market_cap_tier": "large"},
    {"rank": 63, "symbol": "COST", "company": "Costco Wholesale Corp", "market_cap_tier": "large"},
    {"rank": 64, "symbol": "IBM", "company": "IBM", "market_cap_tier": "large"},
    {"rank": 65, "symbol": "TMO", "company": "Thermo Fisher Scientific", "market_cap_tier": "large"},
    {"rank": 66, "symbol": "ACN", "company": "Accenture plc", "market_cap_tier": "large"},
    {"rank": 67, "symbol": "QCOM", "company": "Qualcomm Inc.", "market_cap_tier": "large"},
    {"rank": 68, "symbol": "TXN", "company": "Texas Instruments Inc.", "market_cap_tier": "large"},
    {"rank": 69, "symbol": "UNP", "company": "Union Pacific Corp", "market_cap_tier": "large"},
    {"rank": 70, "symbol": "UNH", "company": "UnitedHealth Group Inc.", "market_cap_tier": "large"},
    {"rank": 71, "symbol": "VZ", "company": "Verizon Communications Inc.", "market_cap_tier": "large"},
    {"rank": 72, "symbol": "T", "company": "AT&T Inc.", "market_cap_tier": "large"},
    {"rank": 73, "symbol": "CMCSA", "company": "Comcast Corp", "market_cap_tier": "large"},
    {"rank": 74, "symbol": "BA", "company": "Boeing Co.", "market_cap_tier": "large"},
    {"rank": 75, "symbol": "NKE", "company": "Nike Inc.", "market_cap_tier": "large"},
    
    # 76-100: Large Cap Tier 3
    {"rank": 76, "symbol": "INTC", "company": "Intel Corporation", "market_cap_tier": "large"},
    {"rank": 77, "symbol": "PG", "company": "Procter & Gamble Co.", "market_cap_tier": "large"},
    {"rank": 78, "symbol": "HD", "company": "Home Depot Inc.", "market_cap_tier": "large"},
    {"rank": 79, "symbol": "CVX", "company": "Chevron Corp", "market_cap_tier": "large"},
    {"rank": 80, "symbol": "SHEL", "company": "Shell plc", "market_cap_tier": "large"},
    {"rank": 81, "symbol": "TTE", "company": "TotalEnergies SE", "market_cap_tier": "large"},
    {"rank": 82, "symbol": "BP", "company": "BP plc", "market_cap_tier": "large"},
    {"rank": 83, "symbol": "BABA", "company": "Alibaba Group Holding Ltd", "market_cap_tier": "large"},
    {"rank": 84, "symbol": "RELIANCE.NS", "company": "Reliance Industries Ltd", "market_cap_tier": "large"},
    {"rank": 85, "symbol": "TCS.NS", "company": "Tata Consultancy Services", "market_cap_tier": "large"},
    {"rank": 86, "symbol": "HDFCBANK.NS", "company": "HDFC Bank Ltd", "market_cap_tier": "large"},
    {"rank": 87, "symbol": "ICICIBANK.NS", "company": "ICICI Bank Ltd", "market_cap_tier": "large"},
    {"rank": 88, "symbol": "INFY.NS", "company": "Infosys Ltd", "market_cap_tier": "large"},
    {"rank": 89, "symbol": "SBIN.NS", "company": "SBI (State Bank of India)", "market_cap_tier": "large"},
    {"rank": 90, "symbol": "BHARTIARTL.NS", "company": "Bharti Airtel Ltd", "market_cap_tier": "large"},
    {"rank": 91, "symbol": "OR.PA", "company": "L'Oréal S.A.", "market_cap_tier": "large"},
    {"rank": 92, "symbol": "ASML", "company": "ASML Holding N.V.", "market_cap_tier": "large"},
    {"rank": 93, "symbol": "SAP.DE", "company": "SAP SE", "market_cap_tier": "large"},
    {"rank": 94, "symbol": "SIE.DE", "company": "Siemens AG", "market_cap_tier": "large"},
    {"rank": 95, "symbol": "VOW3.DE", "company": "Volkswagen AG", "market_cap_tier": "large"},
    {"rank": 96, "symbol": "MBG.DE", "company": "Mercedes-Benz Group AG", "market_cap_tier": "large"},
    {"rank": 97, "symbol": "BMW.DE", "company": "BMW AG", "market_cap_tier": "large"},
    {"rank": 98, "symbol": "SU.PA", "company": "Schneider Electric SE", "market_cap_tier": "large"},
    {"rank": 99, "symbol": "MC.PA", "company": "LVMH Moët Hennessy Louis Vuitton", "market_cap_tier": "large"},
    {"rank": 100, "symbol": "CDI.PA", "company": "Christian Dior SE", "market_cap_tier": "large"},
    
    # 101-200: Mid Cap Companies
    {"rank": 101, "symbol": "SYK", "company": "Stryker Corporation", "market_cap_tier": "mid"},
    {"rank": 102, "symbol": "CRWD", "company": "CrowdStrike Holdings, Inc.", "market_cap_tier": "mid"},
    {"rank": 103, "symbol": "LOW", "company": "Lowe's Companies, Inc.", "market_cap_tier": "mid"},
    {"rank": 104, "symbol": "DE", "company": "Deere & Company", "market_cap_tier": "mid"},
    {"rank": 105, "symbol": "WELL", "company": "Welltower Inc.", "market_cap_tier": "mid"},
    {"rank": 106, "symbol": "SPOT", "company": "Spotify Technology S.A.", "market_cap_tier": "mid"},
    {"rank": 107, "symbol": "HOOD", "company": "Robinhood Markets, Inc.", "market_cap_tier": "mid"},
    {"rank": 108, "symbol": "HON", "company": "Honeywell International Inc.", "market_cap_tier": "mid"},
    {"rank": 109, "symbol": "PGR", "company": "The Progressive Corporation", "market_cap_tier": "mid"},
    {"rank": 110, "symbol": "C", "company": "Citigroup Inc.", "market_cap_tier": "mid"},
    {"rank": 111, "symbol": "GS", "company": "Goldman Sachs Group, Inc.", "market_cap_tier": "mid"},
    {"rank": 112, "symbol": "AMT", "company": "American Tower Corporation", "market_cap_tier": "mid"},
    {"rank": 113, "symbol": "PLTR", "company": "Palantir Technologies Inc.", "market_cap_tier": "mid"},
    {"rank": 114, "symbol": "DHR", "company": "Danaher Corporation", "market_cap_tier": "mid"},
    {"rank": 115, "symbol": "ABT", "company": "Abbott Laboratories", "market_cap_tier": "mid"},
    {"rank": 116, "symbol": "BHP", "company": "BHP Group Limited", "market_cap_tier": "mid"},
    {"rank": 117, "symbol": "TD", "company": "The Toronto-Dominion Bank", "market_cap_tier": "mid"},
    {"rank": 118, "symbol": "F", "company": "Ford Motor Company", "market_cap_tier": "mid"},
    {"rank": 119, "symbol": "GM", "company": "General Motors Company", "market_cap_tier": "mid"},
    {"rank": 120, "symbol": "HYMTF", "company": "Hyundai Motor Company", "market_cap_tier": "mid"},
    {"rank": 121, "symbol": "000270.KS", "company": "Kia Corporation", "market_cap_tier": "mid"},
    {"rank": 122, "symbol": "FDX", "company": "FedEx Corporation", "market_cap_tier": "mid"},
    {"rank": 123, "symbol": "UPS", "company": "United Parcel Service, Inc.", "market_cap_tier": "mid"},
    {"rank": 124, "symbol": "MMM", "company": "3M Company", "market_cap_tier": "mid"},
    {"rank": 125, "symbol": "GSK", "company": "GlaxoSmithKline plc", "market_cap_tier": "mid"},
    {"rank": 126, "symbol": "SAN", "company": "Sanofi", "market_cap_tier": "mid"},
    {"rank": 127, "symbol": "MDT", "company": "Medtronic plc", "market_cap_tier": "mid"},
    {"rank": 128, "symbol": "SPG", "company": "Simon Property Group, Inc.", "market_cap_tier": "mid"},
    {"rank": 129, "symbol": "TGT", "company": "Target Corporation", "market_cap_tier": "mid"},
    {"rank": 130, "symbol": "INDITEX", "company": "Inditex (Zara)", "market_cap_tier": "mid"},
    {"rank": 131, "symbol": "HM-B.ST", "company": "H&M Hennes & Mauritz AB", "market_cap_tier": "mid"},
    {"rank": 132, "symbol": "ORAN", "company": "Orange S.A.", "market_cap_tier": "mid"},
    {"rank": 133, "symbol": "VOD", "company": "Vodafone Group plc", "market_cap_tier": "mid"},
    {"rank": 134, "symbol": "AMX", "company": "América Móvil, S.A.B. de C.V.", "market_cap_tier": "mid"},
    {"rank": 135, "symbol": "BK", "company": "The Bank of New York Mellon Corporation", "market_cap_tier": "mid"},
    {"rank": 136, "symbol": "ABNB", "company": "Airbnb, Inc.", "market_cap_tier": "mid"},
    {"rank": 137, "symbol": "GLW", "company": "Corning Incorporated", "market_cap_tier": "mid"},
    {"rank": 138, "symbol": "CTAS", "company": "Cintas Corporation", "market_cap_tier": "mid"},
    {"rank": 139, "symbol": "EMR", "company": "Emerson Electric Co.", "market_cap_tier": "mid"},
    {"rank": 140, "symbol": "NGG", "company": "National Grid plc", "market_cap_tier": "mid"},
    {"rank": 141, "symbol": "ING", "company": "ING Groep N.V.", "market_cap_tier": "mid"},
    {"rank": 142, "symbol": "AON", "company": "Aon plc", "market_cap_tier": "mid"},
    {"rank": 143, "symbol": "BCS", "company": "Barclays PLC", "market_cap_tier": "mid"},
    {"rank": 144, "symbol": "TEL", "company": "TE Connectivity plc", "market_cap_tier": "mid"},
    {"rank": 145, "symbol": "ECL", "company": "Ecolab Inc.", "market_cap_tier": "mid"},
    {"rank": 146, "symbol": "MSTR", "company": "MicroStrategy Inc", "market_cap_tier": "mid"},
    {"rank": 147, "symbol": "VRT", "company": "Vertiv Holdings Co", "market_cap_tier": "mid"},
    {"rank": 148, "symbol": "USB", "company": "U.S. Bancorp", "market_cap_tier": "mid"},
    {"rank": 149, "symbol": "MDLZ", "company": "Mondelez International, Inc.", "market_cap_tier": "mid"},
    {"rank": 150, "symbol": "RACE", "company": "Ferrari N.V.", "market_cap_tier": "mid"},
    {"rank": 151, "symbol": "PNC", "company": "The PNC Financial Services Group, Inc.", "market_cap_tier": "mid"},
    {"rank": 152, "symbol": "RBLX", "company": "Roblox Corporation", "market_cap_tier": "mid"},
    {"rank": 153, "symbol": "TDG", "company": "TransDigm Group Incorporated", "market_cap_tier": "mid"},
    {"rank": 154, "symbol": "ITW", "company": "Illinois Tool Works Inc.", "market_cap_tier": "mid"},
    {"rank": 155, "symbol": "BKNG", "company": "Booking Holdings Inc.", "market_cap_tier": "mid"},
    {"rank": 156, "symbol": "REGN", "company": "Regeneron Pharmaceuticals, Inc.", "market_cap_tier": "mid"},
    {"rank": 157, "symbol": "ZTS", "company": "Zoetis Inc.", "market_cap_tier": "mid"},
    {"rank": 158, "symbol": "NEE", "company": "NextEra Energy, Inc.", "market_cap_tier": "mid"},
    {"rank": 159, "symbol": "SO", "company": "The Southern Company", "market_cap_tier": "mid"},
    {"rank": 160, "symbol": "EXC", "company": "Exelon Corporation", "market_cap_tier": "mid"},
    {"rank": 161, "symbol": "DUK", "company": "Duke Energy Corporation", "market_cap_tier": "mid"},
    {"rank": 162, "symbol": "AEP", "company": "American Electric Power Company", "market_cap_tier": "mid"},
    {"rank": 163, "symbol": "D", "company": "Dominion Energy, Inc.", "market_cap_tier": "mid"},
    {"rank": 164, "symbol": "PCG", "company": "Pacific Gas & Electric Co.", "market_cap_tier": "mid"},
    {"rank": 165, "symbol": "XEL", "company": "Xcel Energy Inc.", "market_cap_tier": "mid"},
    {"rank": 166, "symbol": "WEC", "company": "WEC Energy Group, Inc.", "market_cap_tier": "mid"},
    {"rank": 167, "symbol": "ED", "company": "Consolidated Edison, Inc.", "market_cap_tier": "mid"},
    {"rank": 168, "symbol": "ETR", "company": "Entergy Corporation", "market_cap_tier": "mid"},
    {"rank": 169, "symbol": "PPL", "company": "PPL Corporation", "market_cap_tier": "mid"},
    {"rank": 170, "symbol": "AES", "company": "The AES Corporation", "market_cap_tier": "mid"},
    {"rank": 171, "symbol": "CNP", "company": "CenterPoint Energy, Inc.", "market_cap_tier": "mid"},
    {"rank": 172, "symbol": "CMS", "company": "CMS Energy Corporation", "market_cap_tier": "mid"},
    {"rank": 173, "symbol": "DTE", "company": "DTE Energy Co.", "market_cap_tier": "mid"},
    {"rank": 174, "symbol": "AWK", "company": "American Water Works Company", "market_cap_tier": "mid"},
    {"rank": 175, "symbol": "WTR", "company": "Aqua America, Inc.", "market_cap_tier": "mid"},
    {"rank": 176, "symbol": "SJM", "company": "The J. M. Smucker Company", "market_cap_tier": "mid"},
    {"rank": 177, "symbol": "K", "company": "Kellogg Company", "market_cap_tier": "mid"},
    {"rank": 178, "symbol": "GIS", "company": "General Mills, Inc.", "market_cap_tier": "mid"},
    {"rank": 179, "symbol": "CAG", "company": "Conagra Brands, Inc.", "market_cap_tier": "mid"},
    {"rank": 180, "symbol": "CPB", "company": "Campbell Soup Company", "market_cap_tier": "mid"},
    {"rank": 181, "symbol": "HRL", "company": "Hormel Foods Corporation", "market_cap_tier": "mid"},
    {"rank": 182, "symbol": "TSN", "company": "Tyson Foods, Inc.", "market_cap_tier": "mid"},
    {"rank": 183, "symbol": "PKG", "company": "Packaging Corporation of America", "market_cap_tier": "mid"},
    {"rank": 184, "symbol": "WRK", "company": "WestRock Company", "market_cap_tier": "mid"},
    {"rank": 185, "symbol": "IP", "company": "International Paper Company", "market_cap_tier": "mid"},
    {"rank": 186, "symbol": "KMB", "company": "Kimberly-Clark Corporation", "market_cap_tier": "mid"},
    {"rank": 187, "symbol": "CLX", "company": "The Clorox Company", "market_cap_tier": "mid"},
    {"rank": 188, "symbol": "CHD", "company": "Church & Dwight Co., Inc.", "market_cap_tier": "mid"},
    {"rank": 189, "symbol": "EL", "company": "The Estée Lauder Companies Inc.", "market_cap_tier": "mid"},
    {"rank": 190, "symbol": "UL", "company": "Unilever PLC", "market_cap_tier": "mid"},
    {"rank": 191, "symbol": "CL", "company": "Colgate-Palmolive Company", "market_cap_tier": "mid"},
    {"rank": 192, "symbol": "PEG", "company": "Public Service Enterprise Group", "market_cap_tier": "mid"},
    {"rank": 193, "symbol": "FE", "company": "FirstEnergy Corp.", "market_cap_tier": "mid"},
    {"rank": 194, "symbol": "ES", "company": "Eversource Energy", "market_cap_tier": "mid"},
    {"rank": 195, "symbol": "ATO", "company": "Atmos Energy Corporation", "market_cap_tier": "mid"},
    {"rank": 196, "symbol": "NI", "company": "NiSource Inc.", "market_cap_tier": "mid"},
    {"rank": 197, "symbol": "LNT", "company": "Alliant Energy Corporation", "market_cap_tier": "mid"},
    {"rank": 198, "symbol": "OGE", "company": "OGE Energy Corp.", "market_cap_tier": "mid"},
    {"rank": 199, "symbol": "MDU", "company": "MDU Resources Group, Inc.", "market_cap_tier": "mid"},
    {"rank": 200, "symbol": "BKH", "company": "Black Hills Corporation", "market_cap_tier": "mid"},
]

# Extract just US tradeable symbols for Alpha Vantage API calls
US_TRADEABLE_SYMBOLS = [
    company["symbol"] for company in TOP_200_COMPANIES 
    if not any(x in company["symbol"] for x in [".SS", ".KS", ".T", ".SW", ".PA", ".L", ".CO", ".TO", ".DE", ".NS", ".AD", ".ST"])
]

# Get symbols by market cap tier
def get_symbols_by_tier(tier: str) -> list:
    """Get symbols filtered by market cap tier"""
    return [
        company["symbol"] for company in TOP_200_COMPANIES 
        if company["market_cap_tier"] == tier and company["symbol"] in US_TRADEABLE_SYMBOLS
    ]

# Priority lists for different data collection strategies
MEGA_CAP_SYMBOLS = get_symbols_by_tier("mega")  # Top 25 - highest priority
LARGE_CAP_SYMBOLS = get_symbols_by_tier("large")  # 26-100 - high priority  
MID_CAP_SYMBOLS = get_symbols_by_tier("mid")  # 101-200 - medium priority

print(f"US Tradeable Symbols: {len(US_TRADEABLE_SYMBOLS)}")
print(f"Mega Cap (1-25): {len(MEGA_CAP_SYMBOLS)}")
print(f"Large Cap (26-100): {len(LARGE_CAP_SYMBOLS)}") 
print(f"Mid Cap (101-200): {len(MID_CAP_SYMBOLS)}")
